### ISSUE TITLE
npm install google-images --save

### ISSUE THREAD

**Issue by stutys** [vadimdemedes/google-images#24]
hi vadimdemedes, thanks for this great work~
I encounter some problems when using your code. I couldn't install google-images any way, i have tried countless way provided by google, but it didn't work. Is there any key point about this topic？

**Comment by vadimdemedes** [comment]
What error are you running into?

**Comment by stutys** [comment]
Thanks for your reply, my problem was solved by collecting images from company database.
I forgot the concrete error, but i think it was about my  computer system version. 
Thanks again.
